spring:
  datasource:
    url: jdbc:h2:mem:transferencias
    driver-class-name: org.h2.Driver
    username: tokio
    password: tokio
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true